# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 09:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pestyle.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=32)),
                ('last_name', models.CharField(blank=True, max_length=32, null=True)),
                ('email', models.EmailField(max_length=64, unique=True)),
                ('sex', models.CharField(choices=[('M', 'male'), ('F', 'female')], default='female', max_length=1)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('city', models.IntegerField(default=1)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=pestyle.models.PathAndRename('avatar/'))),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('event_type', models.CharField(choices=[('C', 'casual'), ('B', 'bussines'), ('S', 'sport'), ('P', 'party')], max_length=1)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('name', models.CharField(max_length=32)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Calendar',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('', 'type'), ('dress', 'dress'), ('blouse', 'blouse'), ('pants', 'pants'), ('footwear', 'footwear'), ('outerwear', 'outerwear'), ('umbrella', 'umbrella'), ('glasses', 'glasses'), ('bag', 'bag'), ('skirt', 'skirt'), ('cap', 'cap'), ('tshirt', 'Tshirt'), ('sneakers', 'Sneakers'), ('shoes', 'Shoes'), ('boots', 'Boots')], max_length=16)),
                ('photo', models.ImageField(upload_to=pestyle.models.PathAndRename('item_photo/'))),
                ('style', models.CharField(choices=[('C', 'casual'), ('B', 'bussines'), ('S', 'sport'), ('P', 'party')], max_length=1)),
                ('color', models.CharField(choices=[('black', 'black'), ('white', 'white'), ('milk', 'milk'), ('beige', 'beige'), ('deep_blue', 'deep_blue'), ('olivaceous', 'olivaceous'), ('deep_green', 'deep_green'), ('vinous', 'vinous'), ('chocolate', 'chocolate'), ('blue', 'blue'), ('pink', 'pink'), ('coral', 'coral'), ('red', 'red'), ('yellow', 'yellow'), ('purple', 'purple'), ('gray', 'gray')], max_length=16)),
                ('season', models.CharField(choices=[('Wn', 'winter'), ('Sp', 'spring'), ('Sm', 'summer'), ('At', 'autumn'), ('SS', 'spring-summer'), ('AW', 'autumn-winter')], max_length=2)),
                ('temperature', models.CharField(choices=[('all', 'all'), ('dubak', '-35_+5'), ('prohladno', '+5_+15'), ('zaebok', '+15_+20'), ('szara', '+20_+35')], max_length=16)),
                ('sky', models.CharField(choices=[('clouds', 'Clouds'), ('rain', 'Rain'), ('clear', 'Clear')], max_length=8)),
                ('last_date', models.DateField(blank=True, null=True)),
                ('rate', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Items',
                'ordering': ['item_type'],
                'get_latest_by': 'last_date',
            },
        ),
        migrations.CreateModel(
            name='Look',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(choices=[('C', 'casual'), ('B', 'bussines'), ('S', 'sport'), ('P', 'party')], max_length=1)),
            ],
            options={
                'db_table': 'Look_like',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Look_suggestions',
            fields=[
                ('look_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pestyle.Look')),
                ('like', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Look_suggestions',
            },
            bases=('pestyle.look',),
        ),
        migrations.AddField(
            model_name='look',
            name='items',
            field=models.ManyToManyField(to='pestyle.Item'),
        ),
        migrations.AddField(
            model_name='look',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['user', 'item_type'], name='Items_user_id_41a024_idx'),
        ),
    ]
