# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-07 13:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=32)),
                ('last_name', models.CharField(blank=True, max_length=32)),
                ('email', models.EmailField(max_length=64, unique=True)),
                ('sex', models.CharField(choices=[('M', 'male'), ('F', 'female')], max_length=1)),
                ('birthday', models.DateField()),
                ('city', models.IntegerField()),
                ('avatar', models.FilePathField(allow_folders=True, blank=True, path='/home/nv/2017_python/msite/pestyle/static/item_photo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('event_type', models.CharField(choices=[('C', 'casual'), ('B', 'bussines'), ('S', 'sport'), ('P', 'party')], max_length=1)),
                ('description', models.CharField(blank=True, max_length=256)),
                ('name', models.CharField(max_length=32)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Calendar',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('dress', 'dress'), ('blouse', 'blouse'), ('pants', 'pants'), ('footwear', 'footwear'), ('outerwear', 'outerwear'), ('umbrella', 'umbrella'), ('glasses', 'glasses'), ('bag', 'bag'), ('skirt', 'skirt'), ('cap', 'cap'), ('T-shirt', 'T-shirt'), ('Sneakers', 'Sneakers'), ('Shoes', 'Shoes'), ('Boots', 'Boots')], max_length=16)),
                ('photo', models.FilePathField(allow_folders=True, path='/home/nv/2017_python/msite/pestyle/static/item_photo')),
                ('style', models.CharField(choices=[('C', 'casual'), ('B', 'bussines'), ('S', 'sport'), ('P', 'party')], max_length=1)),
                ('color', models.CharField(choices=[('black', 'black'), ('white', 'white'), ('milk', 'milk'), ('beige', 'beige'), ('deep_blue', 'deep_blue'), ('olivaceous', 'olivaceous'), ('deep_green', 'deep_green'), ('vinous', 'vinous'), ('chocolate', 'chocolate'), ('blue', 'blue'), ('pink', 'pink'), ('coral', 'coral'), ('red', 'red'), ('yellow', 'yellow'), ('purple', 'purple'), ('gray', 'gray')], max_length=16)),
                ('season', models.CharField(choices=[('Wn', 'winter'), ('Sp', 'spring'), ('Sm', 'summer'), ('At', 'autumn')], max_length=2)),
                ('temperature', models.CharField(choices=[('all', 'all'), ('dubak', '-35_+5'), ('prohladno', '+5_+15'), ('zaebok', '+15_+20'), ('szara', '+20_+35')], max_length=16)),
                ('sky', models.CharField(choices=[('Clouds', 'Clouds'), ('Rain', 'Rain'), ('Clear', 'Clear')], max_length=8)),
                ('last_date', models.DateField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Items',
                'ordering': ['item_type'],
                'get_latest_by': 'last_date',
            },
        ),
        migrations.CreateModel(
            name='Look',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(choices=[('C', 'casual'), ('B', 'bussines'), ('S', 'sport'), ('P', 'party')], max_length=1)),
                ('items', models.ManyToManyField(to='pestyle.Item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Look_like',
            },
        ),
        migrations.AlterIndexTogether(
            name='item',
            index_together=set([('user', 'item_type')]),
        ),
    ]
