# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-23 22:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pestyle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('C', 'повседневный'), ('B', 'деловой'), ('S', 'спорт'), ('P', 'вечеринка')], max_length=1),
        ),
        migrations.AlterField(
            model_name='item',
            name='color',
            field=models.CharField(choices=[('black', 'чёрный'), ('white', 'белый'), ('milk', 'молочный'), ('beige', 'бежевый'), ('deep_blue', 'синий'), ('olivaceous', 'оливковый'), ('deep_green', 'зелёный'), ('vinous', 'бордовый'), ('chocolate', 'шоколадный'), ('blue', 'голубой'), ('pink', 'розовый'), ('coral', 'коралловый'), ('red', 'красный'), ('yellow', 'жёлтый'), ('purple', 'фиолетовый'), ('gray', 'серый')], max_length=16),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('', 'тип'), ('dress', 'платье'), ('blouse', 'блузка'), ('pants', 'брюки'), ('outerwear', 'верхняя одежда'), ('umbrella', 'зонт'), ('glasses', 'очки'), ('bag', 'сумка'), ('skirt', 'юбка'), ('cap', 'головной убор'), ('tshirt', 'футболка'), ('sneakers', 'кроссовки'), ('shoes', 'туфли'), ('boots', 'ботинки')], max_length=16),
        ),
        migrations.AlterField(
            model_name='item',
            name='season',
            field=models.CharField(choices=[('Wn', 'зима'), ('Sp', 'весна'), ('Sm', 'лето'), ('At', 'осень'), ('SS', 'весна-лето'), ('AW', 'осень-зима'), ('WY', 'круглый год')], max_length=2),
        ),
        migrations.AlterField(
            model_name='item',
            name='sky',
            field=models.CharField(choices=[('clouds', 'облачно'), ('rain', 'дождь'), ('clear', 'ясно')], max_length=8),
        ),
        migrations.AlterField(
            model_name='item',
            name='style',
            field=models.CharField(choices=[('C', 'повседневный'), ('B', 'деловой'), ('S', 'спорт'), ('P', 'вечеринка')], max_length=1),
        ),
        migrations.AlterField(
            model_name='item',
            name='temperature',
            field=models.CharField(choices=[('all', 'любая'), ('dubak', 'от -35 до +5'), ('prohladno', 'от +5 до +15'), ('zaebok', 'от +15 до +20'), ('szara', 'от +20 до +35')], max_length=16),
        ),
        migrations.AlterField(
            model_name='look',
            name='style',
            field=models.CharField(choices=[('C', 'повседневный'), ('B', 'деловой'), ('S', 'спорт'), ('P', 'вечеринка')], max_length=1),
        ),
        migrations.AlterField(
            model_name='look_suggestions',
            name='style',
            field=models.CharField(choices=[('C', 'повседневный'), ('B', 'деловой'), ('S', 'спорт'), ('P', 'вечеринка')], max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('M', 'М'), ('F', 'Ж')], default='Ж', max_length=1),
        ),
    ]
