# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pestyle', '0002_auto_20170423_0400'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='look',
            options={'ordering': ['pk']},
        ),
        migrations.AddField(
            model_name='item',
            name='rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='look_suggestions',
            name='like',
            field=models.BooleanField(default=False),
        ),
    ]
