# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 01:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pestyle', '0003_auto_20170423_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('', 'type'), ('dress', 'dress'), ('blouse', 'blouse'), ('pants', 'pants'), ('footwear', 'footwear'), ('outerwear', 'outerwear'), ('umbrella', 'umbrella'), ('glasses', 'glasses'), ('bag', 'bag'), ('skirt', 'skirt'), ('cap', 'cap'), ('tshirt', 'Tshirt'), ('sneakers', 'Sneakers'), ('shoes', 'Shoes'), ('boots', 'Boots')], max_length=16),
        ),
    ]
